### ISSUE TITLE
Numpy doesn't installed correctly on Windows using uv

### ISSUE THREAD

**Issue by kimwonj77** [astral-sh/rye#1206]
### Steps to Reproduce

```
rye init --virtual -p 3.11
rye add "numpy>1, <2"
# Activate VENV
python -c "import numpy; print('Good')"
```

Expected result is `use-uv = false`, Actual resuit is `use-uv = true` on config.toml

Note that somehow, python 3.12.2 doesn't have this issue. But older python result like this. (I have multiple version of python installed on this machine. via conda, python.org installers, mingw or rye)

### Expected Result

```
PS [redacted]\numpy_rye_test> rye init --virtual -p 3.11
success: Initialized virtual project in [redacted]\numpy_rye_test\.
  Run `rye sync` to get started
PS [redacted]\numpy_rye_test> rye add "numpy>1, <2"       
Added numpy>1, <2 as regular dependency
PS [redacted]\numpy_rye_test> rye sync -f                                  
Initializing new virtualenv in [redacted]\numpy_rye_test\.venv
Python version: cpython@3.11.9
Generating production lockfile: [redacted]\numpy_rye_test\requirements.lock
Generating dev lockfile: [redacted]\numpy_rye_test\requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Collecting numpy==1.26.4 (from -r [redacted]\Temp\tmpvpyewsbc (line 1))
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4
Done!
(numpy-rye-test) PS [redacted]\numpy_rye_test> ./.venv/Scripts/Activate.ps1
(numpy-rye-test) PS [redacted]\numpy_rye_test>  python -c "import numpy;"
(numpy-rye-test) PS [redacted]\numpy_rye_test>  python -c "import numpy; print('Good')"
Good
```

### Actual Result

```
PS [redacted]\numpy_rye_test> rye init --virtual -p 3.11
success: Initialized virtual project in [redacted]\numpy_rye_test\.
  Run `rye sync` to get started
PS [redacted]\numpy_rye_test> rye add "numpy>1, <2"
Initializing new virtualenv in [redacted]\numpy_rye_test\.venv
Python version: cpython@3.11.9
Added numpy>1, <2 as regular dependency
Reusing already existing virtualenv
Generating production lockfile: \\?\[redacted]\numpy_rye_test\requirements.lock
Generating dev lockfile: \\?\[redacted]\numpy_rye_test\requirements-dev.lock
Installing dependencies
Resolved 1 package in 7ms
Installed 1 package in 177ms
 + numpy==1.26.4
Done!
PS [redacted]\numpy_rye_test> ./.venv/Scripts/Activate.ps1
(numpy-rye-test) PS [redacted]\numpy_rye_test>  python -c "import numpy;"
Traceback (most recent call last):
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "[redacted]\numpy_rye_test\.venv\Scripts\python.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[redacted]\numpy_rye_test\.venv\Lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
````

### Version Info

```
rye 0.36.0
commit: 0.36.0 (12c024c7c 2024-07-07)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: false
```

**Comment by kimwonj77** [comment]
Seems like Rye somehow ignores current Python version and installs other python version's wheel.
Getting similar issue on other project on `0.37.0` :(
![image](https://github.com/user-attachments/assets/2399574b-72f7-4162-a5a0-2360b17f706c)

**Comment by charliermarsh** [comment]
@kimwonj77 -- Are you on ARM Windows? In the "Expected" trace, pip is selecting an ARM wheel, but the Rye "Version Info" reports `x86_64`.

**Comment by kimwonj77** [comment]
No. It’s x64 machines. And it downloads cp312 version of numpy when I set .python-version to 3.11.9. Also Pip doesn’t (follows current env) but uv does this…

I think there’s cache things broken this. Cause some other projects uses 3.12 version but if I need to use torch, downgraded to 3.11. And that’s what it cause. (Maybe)

**Comment by charliermarsh** [comment]
Sorry, I was misread `amd64` with `arm64` -- ignore my previous comment. Can you try running `uv cache clean` and then trying again?

**Comment by kimwonj77** [comment]
Clear the cache works like a charm. but it increases download speed...

Btw, I can reproduce more easily. 
1. initially set `python-version` to `3.12.3` (and `uv cache clean` for just in case)
2. after `rye sync -f`, see the site-packages' numpy wheel file on venv. it's `cp312`.
3. change `.python-version` to `3.11.9` and `rye sync -f`
4. venv's wheel file still says `cp312` version of numpy
5. now `uv cache clean` and it download cp311 again.

This should be fixed, for my case, i'm switching python version very often due to compability issues. i prefer 3.12 but may libraries are (often) still needs 3.11...
