### ISSUE TITLE
Cannot use matplotlib

### ISSUE THREAD

**Issue by jreniel** [astral-sh/rye#1366]
### Steps to Reproduce

Add matplotlib to your dependencies, try to use TkAgg:
```python
import matplotlib
matplotlib.use("TkAgg")
```
OR
```python
import matplotlib.pyplot as plt
plt.plot([0], [0])
plt.show()        
```

### Expected Result

A plot should appear

### Actual Result

We get problems with TkInter not loading.
![image](https://github.com/user-attachments/assets/9cecdf0c-ea03-419d-a1f3-6f742e30f23f)

### Version Info

rye 0.39.0
commit: 0.39.0 (bf3ccf818 2024-08-21)
platform: linux (x86_64)
self-python: cpython@3.12.5
symlink support: true
uv enabled: true

**Comment by my1e5** [comment]
Related to https://github.com/astral-sh/uv/issues/6893

**Comment by baristahell** [comment]
Yeah same, and I can't seem to find what's going on. Resorted to saving figs in a temp dir but this is super dirty. 

> AttributeError: module '_tkinter' has no attribute '__file__'. Did you mean: '__name__'?
> The above exception was the direct cause of the following exception:
> ImportError: failed to load tkinter functions
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "SOMEPLACE/.venv/lib/python3.10/site-packages/matplotlib/__init__.py", line 1281, in use
>     plt.switch_backend(name)
>   File "SOMEPLACE/.venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 425, in switch_backend
>     module = backend_registry.load_backend_module(newbackend)
>   File "SOMEPLACE/.venv/lib/python3.10/site-packages/matplotlib/backends/registry.py", line 317, in load_backend_module
>     return importlib.import_module(module_name)
>   File "HOME/.rye/py/cpython@3.10.14/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "SOMEPLACE/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
>     from . import _backend_tk
>   File "SOMEPLACE/.venv/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 25, in <module>
>     from . import _tkagg
> ImportError: initialization failed

**Comment by jreniel** [comment]
rye is in principle a good idea, but this issue has made me step away from it, particularly because this has been open since forever and hasn't received any attention. For me this is a super deal-breaker because verification plotting is central to my workflow.

**Comment by charliermarsh** [comment]
We're tracking all issues like this in uv. You should follow https://github.com/astral-sh/uv/issues/6893 instead.

**Comment by jreniel** [comment]
@charliermarsh Thanks! I'm glad this is being taken care of. Closing.
