### ISSUE TITLE
Workspace dependencies clash with builtins

### ISSUE THREAD

**Issue by mihalikv** [astral-sh/rye#772]
### Steps to Reproduce

1. clone repository https://github.com/mihalikv/improved-umbrella
2. run `rye sync`

### Expected Result

**With uv**: successful installation

### Actual Result

When **uv** is disabled: it just works.

When **uv** is enabled:
```
vilo@Vilo:~/test_project$ rye sync
Reusing already existing virtualenv
Generating production lockfile: /home/vilo/test_project/requirements.lock
error: Failed to build editables
  Caused by: Failed to build editable: file:///home/vilo/test_project/nested_lib
  Caused by: Build backend failed to build wheel through `build_editable()`:
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/build.py", line 82, in build_editable
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 244, in validate_fields
    self.core.validate_fields()
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1334, in validate_fields
    getattr(self, attribute)
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1207, in dependencies
    self._dependencies = list(self.dependencies_complex)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1158, in dependencies_complex
    from packaging.requirements import InvalidRequirement, Requirement
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 7, in <module>
    from ._parser import parse_requirement as _parse_requirement
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/_parser.py", line 10, in <module>
    from ._tokenizer import DEFAULT_RULES, Tokenizer
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/_tokenizer.py", line 6, in <module>    from .specifiers import Specifier
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/specifiers.py", line 26, in <module>
    from .utils import canonicalize_version
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/home/vilo/.cache/uv/.tmp30t7GI/.venv/lib/python3.11/site-packages/packaging/tags.py", line 27, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'
---
error: could not write production lockfile for workspace

Caused by:
    failed to generate lockfile
```

### Version Info

```
rye 0.26.0
commit: 0.26.0 (d245f625e 2024-02-23)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: false
```

**Comment by mitsuhiko** [comment]
This would be a bug in uv. Can be reproduced from that repo:

```
$ uv pip compile requirements.lock
error: Failed to build editables
  Caused by: Failed to build editable: file:///private/tmp/improved-umbrella/nested_lib
  Caused by: Build backend failed to build wheel through `build_editable()`:
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/build.py", line 82, in build_editable
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 244, in validate_fields
    self.core.validate_fields()
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1334, in validate_fields
    getattr(self, attribute)
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1207, in dependencies
    self._dependencies = list(self.dependencies_complex)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1158, in dependencies_complex
    from packaging.requirements import InvalidRequirement, Requirement
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 7, in <module>
    from ._parser import parse_requirement as _parse_requirement
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/_parser.py", line 10, in <module>
    from ._tokenizer import DEFAULT_RULES, Tokenizer
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/_tokenizer.py", line 6, in <module>
    from .specifiers import Specifier
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/specifiers.py", line 26, in <module>
    from .utils import canonicalize_version
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/Users/mitsuhiko/Library/Caches/uv/.tmpAQYEa4/.venv/lib/python3.11/site-packages/packaging/tags.py", line 27, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'
---
```

Contents of requirements.txt:

```
# generated by rye
# use `rye lock` or `rye sync` to update this lockfile
#
# last locked with the following flags:
#   pre: false
#   features: []
#   all-features: false
#   with-sources: false

-e file:nested_lib
-e file:.
asgiref==3.7.2
    # via django
django==5.0.2
    # via nested-lib
sqlparse==0.4.4
    # via django
```
