### ISSUE TITLE
Adding local packages to virtual projects triggers panic

### ISSUE THREAD

**Issue by ma-sadeghi** [astral-sh/rye#782]
### Steps to Reproduce

```shell
# Clone a repository to be used as a local package
git clone https://github.com/AUTODIAL/AutoEIS/
mkdir proj
cd proj
rye init --virtual
rye add autoeis --path ../AutoEIS/
```

### Expected Result

AutoEIS to be successfully added as a local dependency

### Actual Result

Rust thread panic

### Version Info

```shell
❯ rye --version
rye 0.26.0
commit: 0.26.0 (d245f625e 2024-02-23)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
```

#### `RUST_BACKTRACE=1`

```shell
❯ RUST_BACKTRACE=1 rye add autoeis --path ../AutoEIS/
thread 'main' panicked at rye/src/cli/add.rs:159:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: rye::cli::add::ReqExtras::apply_to_requirement
   4: rye::cli::add::execute
   5: rye::cli::execute
   6: rye::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

#### `RUST_BACKTRACE=full`

```shell
❯ RUST_BACKTRACE=full rye add autoeis --path ../AutoEIS/
thread 'main' panicked at rye/src/cli/add.rs:159:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x77bc6754ebe6 - std::backtrace_rs::backtrace::libunwind::trace::h7d9d6777fb8bb20d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x77bc6754ebe6 - std::backtrace_rs::backtrace::trace_unsynchronized::h9c973399eff3243c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x77bc6754ebe6 - std::sys_common::backtrace::_print_fmt::hcfcb0438b59f41ac
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x77bc6754ebe6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h12ff509796e7db1f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x77bc6759d940 - core::fmt::rt::Argument::fmt::h0f89a5eb60e0da5a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x77bc6759d940 - core::fmt::write::hd2897b7ab92710d9
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x77bc6754abdf - std::io::Write::write_fmt::h7aec362f631668c1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x77bc6754e9c4 - std::sys_common::backtrace::_print::h02de5e3a7ec93331
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x77bc6754e9c4 - std::sys_common::backtrace::print::h39dfbda16576800a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x77bc67550877 - std::panicking::default_hook::{{closure}}::h9d3976e3cec30e20
  10:     0x77bc675505d9 - std::panicking::default_hook::h8f0238c5452f23e8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x77bc67550d08 - std::panicking::rust_panic_with_hook::hc412fca92650d4b2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x77bc67550ba9 - std::panicking::begin_panic_handler::{{closure}}::hf6e9952ead3e2c54
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:     0x77bc6754f0e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h1410a9c85ac94b3e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x77bc67550940 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x77bc66d4c565 - core::panicking::panic_fmt::h2838d0515af9b2ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x77bc66d4c623 - core::panicking::panic::h584a128616e7fa9b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  17:     0x77bc66e301e0 - rye::cli::add::ReqExtras::apply_to_requirement::h614aa4a1fe52f326
  18:     0x77bc66e30aea - rye::cli::add::execute::hcc566327b63f3edd
  19:     0x77bc66e967c5 - rye::cli::execute::hbc2a77f489ec6cc4
  20:     0x77bc66e78bb6 - rye::main::he8687192c00d17a6
  21:     0x77bc66e694a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf9c4fdada04b3200
  22:     0x77bc66e02d99 - std::rt::lang_start::{{closure}}::ha50bb52414454e14
  23:     0x77bc67542848 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbd70bf23aaabb1f2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  24:     0x77bc67542848 - std::panicking::try::do_call::h34a2aa1a42d8b296
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  25:     0x77bc67542848 - std::panicking::try::ha9060f095dce4b29
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  26:     0x77bc67542848 - std::panic::catch_unwind::h6bae8dd14d964496
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  27:     0x77bc67542848 - std::rt::lang_start_internal::{{closure}}::h4ced5aadb57c4e33
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  28:     0x77bc67542848 - std::panicking::try::do_call::hb890e897357f772c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  29:     0x77bc67542848 - std::panicking::try::h795efaa1580fa0bb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  30:     0x77bc67542848 - std::panic::catch_unwind::hcdb55523e22a6b5f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  31:     0x77bc67542848 - std::rt::lang_start_internal::h6c2766cc18ac837a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  32:     0x77bc66e78e05 - main
```

**Comment by mitsuhiko** [comment]
Probably rubs into this: https://github.com/astral-sh/rye/blob/ad705d073909fdd6d32a945699719442dbff67fe/rye/src/cli/add.rs#L173
