### ISSUE TITLE
Odd `rye build` error in GA

### ISSUE THREAD

**Issue by RitikShah** [astral-sh/rye#873]
### Steps to Reproduce

1. [Repo](https://github.com/Smithed-MC/smithed-python/actions/runs/8237706998/job/22527039448)
2. I just run `rye build` as apart of `python-semantic-version`. this runs via `bash -c rye build`.
3. This occurs on commit for my auto-release

### Expected Result

It should build into `dist`.

### Actual Result

```py
tarfile.AbsoluteLinkError: 'smithed-0.15.0/.rye/self/bin/python' is a link to an absolute path
ERROR 'smithed-0.15.0/.rye/self/bin/python' is a link to an absolute path
```

### Version Info

0.29.0

### Stacktrace
```py
Traceback (most recent call last):
  File "/home/runner/work/smithed-python/smithed-python/.rye/self/lib/python3.12/site-packages/build/__main__.py", line 388, in main
    built = build_call(
            ^^^^^^^^^^^
  File "/home/runner/work/smithed-python/smithed-python/.rye/self/lib/python3.12/site-packages/build/__main__.py", line [24](https://github.com/Smithed-MC/smithed-python/actions/runs/8237706998/job/22527039448#step:9:25)7, in build_package_via_sdist
    t.extractall(sdist_out)
  File "/home/runner/work/smithed-python/smithed-python/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2[26](https://github.com/Smithed-MC/smithed-python/actions/runs/8237706998/job/22527039448#step:9:27)1, in extractall
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/smithed-python/smithed-python/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2315, in _get_extract_tarinfo
    self._handle_fatal_error(e)
  File "/home/runner/work/smithed-python/smithed-python/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2313, in _get_extract_tarinfo
    tarinfo = filter_function(tarinfo, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/smithed-python/smithed-python/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 8[28](https://github.com/Smithed-MC/smithed-python/actions/runs/8237706998/job/22527039448#step:9:29), in data_filter
    new_attrs = _get_filtered_attrs(member, dest_path, True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/smithed-python/smithed-python/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 805, in _get_filtered_attrs
    raise AbsoluteLinkError(member)
tarfile.AbsoluteLinkError: 'smithed-0.15.0/.rye/self/bin/python' is a link to an absolute path
ERROR 'smithed-0.15.0/.rye/self/bin/python' is a link to an absolute path
```

**Comment by mitsuhiko** [comment]
What I think is happening is that `HOME` is set to `smithed-0.15.0` for some reason which means that Rye ends up in `smithed-0.15.0/.rye` and then it tries to package up itself?

**Comment by RitikShah** [comment]
I tried deleting cache to no avail, sometimes that causes issues. Not sure how `$HOME` would bet set to that tough.

**Comment by RitikShah** [comment]
> I just noticed that you are using the rye github action. A very similar looking bug was resolved in v2: https://github.com/eifinger/setup-rye/releases/tag/v2.0.0
> 
> Try changing to `eifinger/setup-rye@v2`

gah, i usually try to make sure i'm on the latest versions but i missed this. fixed! (time to fix the next bug 🔨!
