### ISSUE TITLE
Build fails after sync - tarfile.AbsoluteLinkError

### ISSUE THREAD

**Issue by brad-alexander** [astral-sh/rye#889]
### Steps to Reproduce

1. `rye init --script hft`
2. `cd hft`
3. `rye build` works
4. `rye sync`
5. `rye build` fails with `tarfile.AbsoluteLinkError: 'hft-0.1.0/.venv/bin/python' is a link to an absolute path`

```shell
rye init --script hft
success: Initialized project in /Users/ba/ws/k8s/hft
  Run `rye sync` to get started
```

```shell
cd hft
```

```shell
rye build

building hft
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for wheel...
* Building wheel...
Successfully built hft-0.1.0.tar.gz and hft-0.1.0-py3-none-any.whl
```

```shell
rye sync

Initializing new virtualenv in /Users/ba/ws/k8s/hft/.venv
Python version: cpython@3.12.2
Generating production lockfile: /Users/ba/ws/k8s/hft/requirements.lock
Generating dev lockfile: /Users/ba/ws/k8s/hft/requirements-dev.lock
Installing dependencies
   Built file:///Users/ba/ws/k8s/hft                                                                                                                                                       Built 1 editable in 136ms
Installed 1 package in 0ms
 + hft==0.1.0 (from file:///Users/ba/ws/k8s/hft)
Done!
```

```shell
rye build

building hft
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...

Traceback (most recent call last):
  File "/Users/ba/.rye/self/lib/python3.12/site-packages/build/__main__.py", line 388, in main
    built = build_call(
            ^^^^^^^^^^^
  File "/Users/ba/.rye/self/lib/python3.12/site-packages/build/__main__.py", line 247, in build_package_via_sdist
    t.extractall(sdist_out)
  File "/Users/ba/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2261, in extractall
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ba/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2315, in _get_extract_tarinfo
    self._handle_fatal_error(e)
  File "/Users/ba/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 2313, in _get_extract_tarinfo
    tarinfo = filter_function(tarinfo, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ba/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 828, in data_filter
    new_attrs = _get_filtered_attrs(member, dest_path, True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ba/.rye/py/cpython@3.12.2/install/lib/python3.12/tarfile.py", line 805, in _get_filtered_attrs
    raise AbsoluteLinkError(member)
tarfile.AbsoluteLinkError: 'hft-0.1.0/.venv/bin/python' is a link to an absolute path

ERROR 'hft-0.1.0/.venv/bin/python' is a link to an absolute path
error: failed to build dist
```

### extra info
<details>
<summary><code>$ cat $(rye config --show-path) / which python / rye --version</code>
</summary>

```shell
[behavior]
use-uv = true
global-python = true

[default]
toolchain = "cpython@3.12"

$ which python
/Users/ba/.rye/shims/python

$ rye --version
rye 0.29.0
commit: 0.29.0 (42b179f36 2024-03-11)
platform: macos (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

</details>

<details>
<summary><code>ls -lat .venv/bin</code>
</summary>

```shell
ls -lat

total 88
-rwxr-xr-x   1 ba  staff   223 Mar 14 15:48 hft
drwxr-xr-x  15 ba  staff   480 Mar 14 15:48 .
drwxr-xr-x@  9 ba  staff   288 Mar 14 15:48 ..
-rw-r--r--   1 ba  staff  2449 Mar 14 15:48 activate_this.py
-rw-r--r--   1 ba  staff  1215 Mar 14 15:48 pydoc.bat
-rw-r--r--   1 ba  staff  1728 Mar 14 15:48 deactivate.bat
-rw-r--r--   1 ba  staff  2236 Mar 14 15:48 activate.bat
-rw-r--r--   1 ba  staff  2768 Mar 14 15:48 activate.ps1
-rw-r--r--   1 ba  staff  3863 Mar 14 15:48 activate.nu
-rw-r--r--   1 ba  staff  4178 Mar 14 15:48 activate.fish
-rw-r--r--   1 ba  staff  2615 Mar 14 15:48 activate.csh
-rw-r--r--   1 ba  staff  3348 Mar 14 15:48 activate
lrwxr-xr-x   1 ba  staff     6 Mar 14 15:48 python3.12 -> python
lrwxr-xr-x   1 ba  staff     6 Mar 14 15:48 python3 -> python
lrwxr-xr-x   1 ba  staff    55 Mar 14 15:48 python -> /Users/ba/.rye/py/cpython@3.12.2/install/bin/python3.12
```

</details>

<details>
<summary><code>cat pyproject.toml</code>
</summary>

```shell
cat pyproject.toml

[project]
name = "hft"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "asdf", email = "asdf@users.noreply.github.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
"hft" = "hft:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/hft"]
```

</details>

### Expected Result

Successfully built hft-0.1.0.tar.gz and hft-0.1.0-py3-none-any.whl

### Actual Result

```python
tarfile.AbsoluteLinkError: 'hft-0.1.0/.venv/bin/python' is a link to an absolute path

ERROR 'hft-0.1.0/.venv/bin/python' is a link to an absolute path
error: failed to build dist
```

### Version Info

```shell
$ rye --version
rye 0.29.0
commit: 0.29.0 (42b179f36 2024-03-11)
platform: macos (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

**Comment by mitsuhiko** [comment]
It sounds like the build process is trying to include the `.venv`. That surprises me.

**Comment by WinChua** [comment]
I meet the same problem. After some debuging, I found that it's because of `.venv` is not in .gitignore, which cause the return of [this code](https://github.com/pypa/hatch/blob/master/backend/src/hatchling/builders/config.py#L98) became true

To solve it, just add the `.venv` into your .gitignore

**Comment by WinChua** [comment]
Another way to solve it, it's to specify all the directories you want to exclude by set the tool.hatch.build.exclude in pyproject.toml, like this:
```
[tool.hatch.build]
exclude = [".venv"]
```
or
```
[tool.hatch.build.targets.sdist]
exclude = [".venv"]
```

So, should we generate such config in pyproject.toml when `rye init`?

**Comment by ischaojie** [comment]
The `rye init` command will automatically generate a `.gitignore` file containing `.venv`. I guess the problem may be that the upper directory is already a `git` directory, causing the `.gitignore` file not to be created during initialization.

**Comment by ischaojie** [comment]
https://hatch.pypa.io/latest/config/build/#vcs It seems that hatch automatically ignores files in `.gitignore` when building.

**Comment by lee-b** [comment]
Just ran into this on my first attempted use of rye.

In my case, I suspect the problem was that I was converting a poetry project to rye, and so there was a pre-existing .gitignore, which didn't get updated with a new .venv line.

Would suggest that a better fix here is to add the specification to pyproject, per https://github.com/astral-sh/rye/issues/889#issuecomment-2009549577. It doesn't seem to make sense to tie rye so tightly to git, when git is a great but flawed (and almost 20 years-old!) tool, and alternatives like pijul are on the horizon.
