### ISSUE TITLE
Unable to Install Rye with Pipx

### ISSUE THREAD

**Issue by Eutropios** [astral-sh/rye#935]
### Steps to Reproduce

System: Fedora 39 - KDE 6.0.2

### ~/.zshenv:

```bash
# Installation of rye was attempted with this envvar set to true and to false, both resulting in the error
# forcing usage of venv to install with pip
export PIP_REQUIRE_VIRTUALENV=false
```

Run `pipx install rye`

This error seems related to yaml/pyyaml#736

### Expected Result

Successful installation into pipx.

### Actual Result

Pipx throws the following error:

```bash
Fatal error from pip prevented installation. Full pip output in file:
    /home/noahj/.local/pipx/logs/cmd_2024-03-23_14.48.13_pip_errors.log

pip seemed to fail to build package:
    pyyaml<6.0.0,>=5.1.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: cython_sources

Error installing rye.
```

Investigating the log reveals the following traceback:

```python-traceback
   648.4ms (setup:858): 2024-03-23 14:48:13
   649.6ms (setup:859): /home/noahj/.local/bin/pipx install rye
   649.9ms (setup:860): pipx version is 1.4.3
   650.0ms (setup:861): Default python interpreter is '/usr/bin/python3'
   654.3ms (package_name_from_spec:370): Determined package name: rye
   654.7ms (package_name_from_spec:371): Package name determined in 0.0s
   657.9ms (run_subprocess:168): running /usr/bin/python3 -m venv --without-pip /home/noahj/.local/pipx/venvs/rye
   909.5ms (run_subprocess:190): stdout:
   909.7ms (run_subprocess:192): stderr:
   909.8ms (run_subprocess:193): returncode: 0
   911.6ms (run_subprocess:168): running <checking pip's availability>
   982.4ms (run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f121f767a70>, origin='/home/noahj/.local/pipx/shared/lib64/python3.12/site-packages/pip/__init__.py', submodule_search_locations=['/home/noahj/.local/pipx/shared/lib64/python3.12/site-packages/pip'])
   982.7ms (run_subprocess:193): returncode: 0
   983.8ms (run_subprocess:168): running /home/noahj/.local/pipx/venvs/rye/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  1061.5ms (run_subprocess:190): stdout: /home/noahj/.local/pipx/venvs/rye/lib/python3.12/site-packages
  1061.7ms (run_subprocess:193): returncode: 0
  1062.3ms (run_subprocess:168): running /home/noahj/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  1137.0ms (run_subprocess:190): stdout: /home/noahj/.local/pipx/shared/lib/python3.12/site-packages
  1137.2ms (run_subprocess:193): returncode: 0
  1138.1ms (run_subprocess:168): running /home/noahj/.local/pipx/venvs/rye/bin/python --version
  1146.7ms (run_subprocess:190): stdout: Python 3.12.2
  1146.9ms (run_subprocess:192): stderr:
  1147.0ms (run_subprocess:193): returncode: 0
  1147.7ms (_parsed_package_to_package_or_url:137): cleaned package spec: rye
  1149.3ms (run_subprocess:168): running /home/noahj/.local/pipx/venvs/rye/bin/python -m pip --no-input install rye
 18212.3ms (run_subprocess:193): returncode: 1
 18213.3ms (subprocess_post_check_handle_pip_error:327): '/home/noahj/.local/pipx/venvs/rye/bin/python -m pip --no-input install rye' failed
 18214.4ms (subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
    /home/noahj/.local/pipx/logs/cmd_2024-03-23_14.48.13_pip_errors.log
 18218.8ms (analyze_pip_output:306): pip seemed to fail to build package:
    pyyaml<6.0.0,>=5.1.2
 18219.8ms (rmdir:55): removing directory /home/noahj/.local/pipx/venvs/rye
 18222.5ms (cli:924): PipxError: Error installing rye.
Traceback (most recent call last):
  File "/home/noahj/.local/lib/python3.12/site-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noahj/.local/lib/python3.12/site-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/home/noahj/.local/lib/python3.12/site-packages/pipx/commands/install.py", line 91, in install
    venv.install_package(
  File "/home/noahj/.local/lib/python3.12/site-packages/pipx/venv.py", line 254, in install_package
    raise PipxError(f"Error installing {full_package_description(package_name, package_or_url)}.")
pipx.util.PipxError: Error installing rye.
 18239.7ms (cli:932): pipx finished.
 ```

### Version Info

Current version distributed by PyPI.

**Comment by mitsuhiko** [comment]
Rye cannot be installed from pypi. The `rye` package there is something else entirely.

**Comment by Eutropios** [comment]
> Rye cannot be installed from pypi. The `rye` package there is something else entirely.

Ahh, apologies for the confusion, thanks for the help!
