### ISSUE TITLE
uv can't create .venv for cpython-x86 on Windows

### ISSUE THREAD

**Issue by CatamountJack** [astral-sh/rye#952]
### Steps to Reproduce

1. Installed rye-x86_64-windows.exe for 64bit Intel Windows
2. Selected to use uv
3. Create a project with cpython 3.12.2 - worked great!
4. Tried to create a new project with cpython-x86@3.12.2 (attempting to create a 32-bit python application)
    a.  rye pin cpython-x86@3.12.2
    b.  rye sync

### Expected Result

Creates a .venv using cpython-x86@3.12.2

### Actual Result

```
C:\dev\source\GroupsByDate>rye sync --force --verbose
Python version already downloaded. Skipping.
Initializing new virtualenv in C:\dev\sourceGroupsByDate\.venv
Python version: cpython-x86@3.12.2
  x Querying Python at `C:\Users\abcde\.rye\py\cpython-x86@3.12.2\python.exe` failed with status exit code: 1 with
  | exit code: 1
  | --- stdout:

  | --- stderr:
  | Traceback (most recent call last):
  |   File "<string>", line 1, in <module>
  |   File "\\?\C:\Users\abcde\AppData\Local\uv\cache\.tmp9beAeZ\python\get_interpreter_info.py", line 526, in main
  |     "platform": get_operating_system_and_architecture(),
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "\\?\C:\Users\abcde\AppData\Local\uv\cache\.tmp9beAeZ\python\get_interpreter_info.py", line 418, in
  | get_operating_system_and_architecture
  |     [operating_system, version_arch] = sysconfig.get_platform().split("-", 1)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | ValueError: not enough values to unpack (expected 2, got 1)
  | ---
error: failed creating virtualenv ahead of sync

Caused by:
    0: failed to initialize virtualenv
    1: Failed to create self venv using C:\Users\abcde\.rye\py\cpython-x86@3.12.2\python.exe. uv exited with status: exit code: 1
```

### Version Info

rye 0.31.0
commit: 0.31.0 (72e239b8f 2024-03-22)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true

**Comment by CatamountJack** [comment]
I believe ```sysconfig.get_platform()``` simply returns "win32" when running 32-bit python, hence the ```ValueError: not enough values to unpack (expected 2, got 1)``` when trying do ```sysconfig.get_platform().split("-", 1)```

**Comment by Zander-1024** [comment]
https://docs.python.org/3/library/sysconfig.html

**Comment by CatamountJack** [comment]
This is fixed - works in 0.33.0 with the latest uv (0.1.37) that has the above commit.
